"""AI provider abstraction. Implementations return Pydantic models, never raw strings, and are
always honest about being AI-generated (never claim to be verified/official data)."""
from __future__ import annotations

from abc import ABC, abstractmethod

from app.schemas.ai import ChatMessage, ChecklistResponse

DISCLAIMER = (
    "This content was generated by an AI assistant and is provided for general guidance only. "
    "It is not verified or official information — always confirm requirements, deadlines, and "
    "documents directly with the relevant government agency or organization."
)


class AIProvider(ABC):
    name: str

    @abstractmethod
    async def generate_checklist(self, goal: str, category: str | None) -> ChecklistResponse: ...

    @abstractmethod
    async def chat(self, messages: list[ChatMessage]) -> str: ...
